In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colors
import math
import re
import base64

In [2]:
import Xm

In [3]:
#xm=Xm.Xm(XmlFile='../testdata/FW.XML') # "C:\3S\Modelle\MVV_FW.XML"
xm=Xm.Xm(XmlFile=r'C:\3S\Modelle\MVV_FW.XML')

# LAYR

In [4]:
xm.vLAYR_DATA.sort_values(by=['LFDNR']).head(10)

    LFDNR               NAME                   pk                   tk
87      1           Rücklauf  5627738828676166951  5627738828676166951
84      2            Vorlauf  5591656201334049534  5591656201334049534
71      3            Legende  5414601572711821259  5414601572711821259
19      4        NDD Trassen  4819100190256866365  4819100190256866365
86      5            TL-Nord  5626927889941643519  5626927889941643519
60      6            TL-West  5228811717872993561  5228811717872993561
44      7      TL-Wasserturm  5067782201375311508  5067782201375311508
4       8        TL-Klinikum  4651722301100862555  4651722301100862555
12      9          Stationen  4769659239151913581  4769659239151913581
14     10  Ergebnisse global  4777367123468863406  4777367123468863406

In [5]:
xm.vLAYR_OBJS.sort_values(by=['LFDNR','OBJID']).head(10)

        LFDNR                OBJID OBJTYPE
683600      1  4611693481689066743    ROHR
660908      1  4611700510609988221    KNOT
643154      1  4611704445968211280    KNOT
675943      1  4611726401115976534    ROHR
690352      1  4611751633071492605    ROHR
649682      1  4611757631916661743    KNOT
631828      1  4611761876541647041    KNOT
647493      1  4611776586810848879    KNOT
676543      1  4611801465084203368    ROHR
674563      1  4611811392507800249    ROHR

In [8]:
xm.vLAYR_OBJS.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 806267 entries, 0 to 806334
Data columns (total 3 columns):
LFDNR      806267 non-null int64
OBJID      806267 non-null object
OBJTYPE    806267 non-null object
dtypes: int64(1), object(2)
memory usage: 117.6 MB

In [9]:
xm.vLAYR.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 806267 entries, 0 to 806266
Data columns (total 6 columns):
LFDNR      806267 non-null int64
NAME       806267 non-null object
pk         806267 non-null object
tk         806267 non-null object
OBJID      806267 non-null object
OBJTYPE    806267 non-null object
dtypes: int64(1), object(5)
memory usage: 295.9 MB

In [10]:
xm.vLAYR.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 806267 entries, 0 to 806266
Data columns (total 6 columns):
LFDNR      806267 non-null int64
NAME       806267 non-null object
pk         806267 non-null object
tk         806267 non-null object
OBJID      806267 non-null object
OBJTYPE    806267 non-null object
dtypes: int64(1), object(5)
memory usage: 43.1+ MB

In [11]:
xm.vLAYR.sort_values(by=['NAME','LFDNR','OBJTYPE','OBJID']).head()

,LFDNR,NAME,pk,tk,OBJID,OBJTYPE
214445,37,ABN,5096367974484600433,5096367974484600433,4636035280657666578,VERB
214443,37,ABN,5096367974484600433,5096367974484600433,5007835137402288560,VERB
214444,37,ABN,5096367974484600433,5096367974484600433,5471545771145852044,VERB
214446,37,ABN,5096367974484600433,5096367974484600433,5498361255709184646,VERB
214442,37,ABN,5096367974484600433,5096367974484600433,5545908012960938145,VERB

# Model

In [ ]:
df=xm.dataFrames['MODELL']
df.head()

In [ ]:
x=df['MEMOTEXT'].str[:]

In [ ]:
print(x)

In [ ]:
print(x.iloc[0])

In [ ]:
bStr=base64.b64decode(x.iloc[0])
print(bStr)

In [ ]:
bStr.decode('utf-8')

=== LFKT ===

In [ ]:
xm.vLFKT.head()

=== FWVB ===

In [ ]:
xm.vFWVB.head()

In [ ]:
#%matplotlib inline

In [ ]:
plt.close('all')
fig=plt.figure()
ax=plt.subplot()

In [ ]:
xm.vFWVB_Plt_Hist()

In [ ]:
txt=ax.set_xlabel('vFWVB_Plt_Hist')

In [ ]:
plt.show()

# xxxx

In [ ]:
xm.vVKNO.head(5)

In [ ]:
xm.vKNOT.head(5)

In [ ]:
xm.vKNOT[['NAME']].size

In [ ]:
xm.vKNOT[(xm.vKNOT['KTYP'].isin(['QKON']) & xm.vKNOT['QM_EIN'].astype(float)!=0) | xm.vKNOT['KTYP'].isin(['QVAR'])][[
                    'NAME'              
                   ,'CONT'
                   ,'CONT_VKNO' # vVKNO
                   ,'KTYP'
                   ,'LFAKT','QM_EIN','QVAR','QM','QM_min','QM_max'     
                   ,'KVR' 
                   ,'TE','TM'                   
    ]].sort_values(by=['CONT_VKNO','NAME'])

In [ ]:
xm.pRSLW.head()

In [ ]:
xm.dataFrames['NRCV'].columns

In [ ]:
vDPGR=pd.merge(xm.dataFrames['DPGR'],xm.dataFrames['DPGR_BZ'],left_on='pk',right_on='fk')

In [ ]:
vDPGR.columns

In [ ]:
vDPGR=vDPGR[[
        # DPGR
        'NAME'
        # DPGR IDs
       ,'pk_x', 'tk'
        # DPGR_BZ        
    ]]

In [ ]:
vDPGR.rename(columns={'pk_x':'pk'},inplace=True)

In [ ]:
vDPGR=pd.merge(vDPGR,xm.dataFrames['DPGR_ROWS'],left_on='pk',right_on='fk')

In [ ]:
vDPGR.columns

In [ ]:
vDPGR=vDPGR[[
        # DPGR
        'NAME'
        # DPGR_BZ   
        # DPGR_ROWS
       ,'OBJTYPE','NAME1','NAME2','NAME3','ATTRTYPE'
       ,'ADDEND','FACTOR','DEVIATION'
       ,'FLAGS','CLIENT_FLAGS'
       ,'DESCRIPTION','TITLE','UNIT' 
       ,'DATALENGTH', 'DATATYPE'
       ,'LOWER_LIMIT','UPPER_LIMIT'
       ,'OL3COMMAND','EPKZ'
        # DPGR IDs
       ,'pk_x', 'tk_x'  
       ,'fkOBJTYPE'
       # DPGR_ROWS IDs 
       ,'pk_y','tk_y'
    ]]

In [ ]:
cDct=dict(zip(vDPGR,vDPGR))

In [ ]:
vDPGR.rename(columns={'pk_x':'pk','tk':'tk','pk_y':'pkROWS','tk_y':'tkROWS'},inplace=True)

In [ ]:
xm.dataFrames['DPGR_ROWS'].columns

In [ ]:
vDPGR.head()

In [ ]:
pd.merge(vDPGR,xm.dataFrames[vDPGR.apply(lambda row: row.OBJTYPE, axis=1)],left_on='fkOBJTYPE',right_on='pk')

In [ ]:
xm.vKNOT.columns

In [ ]:
sorted(xm.dataFrames.keys())